---
- name: Pull docker image of Calc
  hosts: all
  tasks:
    - name: Remove image
      docker_image:
        name: patro30/calculator-devops
        state: absent
        force: yes
    - name: Pull new image
      docker_image:
        name: patro30/calculator-devops
