---
- name: Pull docker image of Calc
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: patro30/calculator-devops
        source: pull
        state: absent
        force: yes